### PR TITLE
Update fr_FR.lang [WIP]

### PR DESCRIPTION
**Pull request by AegisLesha**
Copied the en_US.lang layout
Will translate this weekend or later this week

### CODE REVIEW

**Comment by Glassmaker** [comment]
okeo, I will pull it in when you are done :)

**Comment by Glassmaker** [comment]
I will pull it in, you can continue on it when you can :)

**Comment by AegisLesha** [comment]
BAHAHA, what a long weekend x)
I'm sorry, I got kinda busy lately :(
Maybe this weekend
Maybe

**Comment by AegisLesha** [comment]
WELP
It may have to wait another weekend :s

**Comment by Glassmaker** [comment]
no worries, take your time :)

**Pull request merged**
